name = "cf-mail"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cf_mail_db"
database_id = "f60b4daa-c415-4592-966e-69a48e944c6c"

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-mail-storage"

[vars]
ADMIN_PASSWORD = "Changeyourpasswordbeforeusingcfmail"
JWT_SECRET = "changeyourjwttokenbeforeusingcfmail"
MAIL_DOMAIN = "example.com,example2.com"

[assets]
directory = "public"
